name: dps_hmex_supervisor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  go_router: ^8.0.1
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  flutter_dotenv: ^5.0.2
  jwt_decoder: ^2.0.1
  http: ^1.1.2
  device_info_plus: ^9.0.3
  package_info_plus: ^4.2.0
  animated_snack_bar: ^0.3.1
  get_it: ^7.2.0
  carousel_slider: ^4.2.1
  localstore: ^1.3.5
  amazon_cognito_identity_dart_2: ^3.6.0
  status_alert: ^1.0.1
  syncfusion_flutter_charts: ^23.2.6
  timer_builder: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: '^0.13.1'
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/img/heineken_icon.png'

flutter:
  uses-material-design:
    true

    # To add assets to your application, add an assets section, like this:

 