name: Commit Notification

on:
  pull_request:
    types:
      - closed

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart dependencies
        run: dart pub get

      - name: Extraer títulos de commits
        id: extract-titles
        run: |
         PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
         if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
         COMMIT_TITLES=$(git log --pretty=format:"%s" HEAD^..HEAD)
         else
         COMMIT_TITLES=$(git log --pretty=format:"%s" -n 1)
         fi

         echo "Commit Titles: $COMMIT_TITLES"
         echo "::set-output name=commit_titles::$COMMIT_TITLES"
          
      - name: Grant execute permissions
        run: chmod +x .github/notion-version/merge-info.dart

      - name: Send Commit Notification to Notion
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          COMMIT_TITLES: ${{ steps.commit_titles.outputs.commit_titles }}
          PR_AUTHOR: ${{ steps.pr_details.outputs.author }}
          PR_TITLE: ${{ steps.pr_details.outputs.title }}
          PR_DATE: ${{ steps.pr_details.outputs.date }}
          PR_NUMBER: ${{ steps.pr_details.outputs.number }}
