name: Commit Notification

on:
  pull_request:
    types:
      - closed

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart dependencies
        run: dart pub get

      - name: Extract commit titles
        id: extract-titles
        run: |
          # Get the SHA of the base commit of the pull request
          BASE_COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
            | jq -r '.base.sha')
          
          echo "Initial Commit SHA: $BASE_COMMIT_SHA"
          
          # Get the commit titles from the base commit to the current commit
          COMMIT_TITLES=$(git rev-list --reverse $BASE_COMMIT_SHA..${{ github.sha }} \
            | xargs -I {} git log --format="%H %s" -n 1 {})
          
          echo "Commit Titles: $COMMIT_TITLES"
          echo "::set-output name=commit_titles::$COMMIT_TITLES"

      - name: Grant execute permissions
        run: chmod +x .github/notion-version/merge-info.dart

      - name: Send Commit Notification to Notion
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          COMMIT_TITLES: ${{ steps.extract-titles.outputs.commit_titles }}
          PR_AUTHOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_DATE: ${{ github.event.pull_request.updated_at }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
