name: Commit Notification

on:
  pull_request:
    types:
      - closed

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: 'PR commits + 1'
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: 'Checkout PR branch and all PR commits'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: 'Imprimir lista de commits'
        run: |
          git log --oneline

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart dependencies
        run: dart pub get

      - name: Extract commit titles
        id: extract-titles
        run: |
          # Get the commit titles from the base commit to the current commit
          COMMIT_TITLES=$(git log --pretty=format:"%H %s" ${{ github.event.before }}..${{ github.sha }})

          if [ -z "$COMMIT_TITLES" ]; then
            echo "No commit titles found."
          else
            echo "Commit Titles: $COMMIT_TITLES"
            echo "::set-output name=commit_titles::$COMMIT_TITLES"
          fi
          
      - name: Grant execute permissions
        run: chmod +x .github/notion-version/merge-info.dart

      - name: Send Commit Notification to Notion
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          COMMIT_TITLES: ${{ steps.extract-titles.outputs.commit_titles }}
          PR_AUTHOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_DATE: ${{ github.event.pull_request.updated_at }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
