name: Commit Notification

on:
  pull_request:
    types:
      - closed

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart dependencies
        run: dart pub get

      - name: Get PR Details
        id: pr_details
        run: |
          echo "::set-output name=author::${{ github.event.pull_request.user.login }}"
          echo "::set-output name=title::${{ github.event.pull_request.title }}"
          echo "::set-output name=date::${{ github.event.pull_request.updated_at }}"
          echo "::set-output name=number::${{ github.event.pull_request.number }}"

      - name: Grant execute permissions
        run: chmod +x .github/notion-version/merge-info.dart
      
      - name: Get Commit Messages
        id: commit_messages
        run: |
          COMMIT_MESSAGES=""
          for commit in $(git rev-list --reverse "${{ github.event.before }}..${{ github.sha }}"); do
            COMMIT_MESSAGES="$COMMIT_MESSAGES$(git log --format=%B -n 1 $commit)%0A"
          done
          echo "::set-output name=commit_messages::${COMMIT_MESSAGES}"

      - name: Send Commit Notification to Notion
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          COMMIT_MESSAGES: ${{ steps.commit_messages.outputs.commit_messages }}
          PR_AUTHOR: ${{ steps.pr_details.outputs.author }}
          PR_TITLE: ${{ steps.pr_details.outputs.title }}
          PR_DATE: ${{ steps.pr_details.outputs.date }}
          PR_NUMBER: ${{ steps.pr_details.outputs.number }}
