name: Commit Notification

on:
  pull_request:
    types:
      - closed

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart dependencies
        run: dart pub get

      - name: Extract commit titles
        id: extract-titles
        run: |
          # Obtener el SHA del commit inicial del pull request
          BASE_COMMIT=$(git rev-list -n 1 ${{ github.event.before }})

          # Obtener los títulos de los commits desde el commit inicial hasta el último commit del pull request
          COMMIT_TITLES=$(git log --pretty=format:"%s" $BASE_COMMIT..${{ github.sha }})

          echo "Commit Titles: $COMMIT_TITLES"
          echo "::set-output name=commit_titles::$COMMIT_TITLES"

      - name: Grant execute permissions
        run: chmod +x .github/notion-version/merge-info.dart

      - name: Send Commit Notification to Notion
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          COMMIT_TITLES: ${{ steps.extract-titles.outputs.commit_titles }}
          PR_AUTHOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_DATE: ${{ github.event.pull_request.updated_at }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
