name: Commit Notification

on:
  push:
    branches:
      - development

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    steps:
      # ... (your existing steps)

      - name: 'Send Commit Notification to Notion'
        run: dart .github/notion-version/merge-info.dart
        env:
          ACTION: MERGE
          PR_AUTHOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.head_commit.message }}
          PR_DATE: ${{ github.event.head_commit.timestamp }}
          PR_NUMBER: ${{ github.run_id }}  # Use a unique identifier if needed
          NOTION_DB: ${{ secrets.NOTION_DB }}
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
